#!/bin/sh
# Matrix anti-rot check (superset sprint 12). Probes every primary's recognition
# across ferret / GNU ref / BSD find / bfs and compares against the recorded
# table (tests/golden/matrix.tab), the machine-readable mirror of
# .docs/superset/matrix.md. Drift means an implementation changed under us or
# ferret's surface moved without the matrix being updated — either way the
# classification must be re-derived, not trusted.
#
#   matrix-check.sh <ferret> <gnu-ref>          check; absent oracles skip loudly
#   matrix-check.sh <ferret> <gnu-ref> --gen    regenerate matrix.tab (needs all
#                                               four oracles; run on the dev box)
#
# Membership is probed empirically, trailing position, one token per run. Each
# implementation has its own unknown-token signature (matching on the wrong one
# is how the first draft misread BSD as recognizing everything):
#   GNU/ferret "unknown predicate" | BSD "unknown primary or operator"
#   bfs        "Unknown argument"
# Values in matrix.tab are always generated by --gen, never hand-edited.
# Leading-only options (-E -s -x -X -f -H -L -P -S -O -D) are not probeable this
# way (BSD parses a leading long token as bundled short flags) and are excluded;
# they are documented in matrix.md only.
#
# Column caveats (recorded in the header, enforced here):
#   bsd: BSD find's surface varies by OS *release*, not just platform (FreeBSD
#        15.1 base find added -xattr/-xattrname; 15.0 lacks them — caught by this
#        check on CI). Column asserted only when OS-release matches the header.
#   bfs: asserted only at the exact recorded version (a tarball build of 4.1.1
#        stamps "4.1"; the pinned build-ref.sh oracle reproduces it everywhere).
set -u
set -f

FER=${1:?usage: matrix-check.sh <ferret> <gnu-ref> [--gen]}
GNU=${2:?usage: matrix-check.sh <ferret> <gnu-ref> [--gen]}
MODE=${3:-check}
here=$(dirname "$0")
tab="$here/matrix.tab"

# The probed union across GNU 4.10.0, BSD find, bfs, and ferret's extensions.
# Coverage list only — recognition values come from the live probe.
TOKENS='-acl -amin -anewer -atime -Bmin -Bnewer -Btime -cmin -cnewer -color
-contains -context -ctime -d -daystart -delete -depth -empty -exclude -exec
-execdir -executable -exit -false -flags -fls -follow -fprint -fprint0 -fprintf
-fstype -gid -group -hidden -icontains -ignore_readdir_race -ilname -iname
-inum -ipath -iregex -iwholename -limit -links -lname -ls -maxdepth -mindepth
-mmin -mnewer -mount -mtime -name -newer -nogroup -nohidden -noleaf -nouser
-nowarn -ok -okdir -path -perm -print -print0 -printf -printx -prune -quit
-readable -regex -regextype -rm -samefile -since -size -sparse -status -true
-type -uid -unique -used -user -warn -wholename -writable -xattr -xattrname
-xdev -xtype'

# Classify a find-like binary by --version: GNU prints its package string, bfs
# its own name, BSD rejects long options outright.
findkind() {
	case "$("$1" --version 2>&1 | head -n 1)" in
	*"GNU findutils"*) echo gnu ;;
	bfs*) echo bfs ;;
	*) echo bsd ;;
	esac
}

FIND_BSD=${FIND_BSD:-}
FIND_BFS=${FIND_BFS:-}
if [ -z "$FIND_BSD" ] && [ -x /usr/bin/find ] && [ "$(findkind /usr/bin/find)" = bsd ]; then
	FIND_BSD=/usr/bin/find
fi
if [ -z "$FIND_BFS" ]; then
	for c in "$(command -v bfs 2>/dev/null || true)" \
	         "$(command -v find 2>/dev/null || true)" tests/.work/ref/bfs; do
		[ -n "$c" ] && [ -x "$c" ] || continue
		[ "$(findkind "$c")" = bfs ] && { FIND_BFS=$c; break; }
	done
fi

T=$(mktemp -d "${TMPDIR:-/tmp}/frtmx.XXXXXX")
touch "$T/f"
trap 'rm -rf "$T"' EXIT INT TERM

# recog <bin> <signature> <token>: Y if the token is recognized (any error other
# than the unknown-token one — e.g. missing-argument — still means recognized).
recog() {
	if LC_ALL=C "$1" "$T" "$3" 2>&1 | grep -qF "$2"; then echo "."; else echo "Y"; fi
}

bfs_ver() { "$1" --version 2>/dev/null | sed -n '1s/^bfs \([0-9.]*\).*/\1/p'; }
os_rel() { printf '%s-%s\n' "$(uname -s)" "$(uname -r | cut -d- -f1)"; }

if [ "$MODE" = "--gen" ]; then
	[ -n "$FIND_BSD" ] && [ -n "$FIND_BFS" ] || {
		echo "matrix-check --gen: needs BSD find and bfs present (dev-box operation)" >&2
		exit 1
	}
	[ "$(uname -s)" = FreeBSD ] || {
		echo "matrix-check --gen: bsd column must be recorded on FreeBSD" >&2
		exit 1
	}
	{
		printf '# generated by matrix-check.sh --gen; do not hand-edit\n'
		printf '# columns: token ferret gnu bsd bfs\n'
		printf '# bsd=%s bfs=%s\n' "$(os_rel)" "$(bfs_ver "$FIND_BFS")"
		for t in $TOKENS; do
			printf '%s %s %s %s %s\n' "$t" \
				"$(recog "$FER" 'unknown predicate' "$t")" \
				"$(recog "$GNU" 'unknown predicate' "$t")" \
				"$(recog "$FIND_BSD" 'unknown primary or operator' "$t")" \
				"$(recog "$FIND_BFS" 'Unknown argument' "$t")"
		done
	} >"$tab"
	echo "matrix-check: wrote $tab ($(grep -vc '^#' "$tab") tokens)"
	exit 0
fi

[ -f "$tab" ] || { echo "matrix-check: no $tab (run --gen on the dev box)"; exit 1; }

# Column gates: environment-specific columns assert only in the environment
# they were recorded in; anywhere else they skip with a note.
want_bsd=$(sed -n 's/^# bsd=\([^ ]*\).*/\1/p' "$tab")
want_bfs=$(sed -n 's/^# bsd=[^ ]* bfs=//p' "$tab")
do_bsd=$FIND_BSD
if [ -n "$FIND_BSD" ] && [ "$(os_rel)" != "$want_bsd" ]; then
	echo "matrix-check: note — bsd column recorded on $want_bsd; this is $(os_rel), skipping it"
	do_bsd=""
fi
[ -z "$FIND_BSD" ] && echo "matrix-check: note — no BSD find here, bsd column skipped"
do_bfs=$FIND_BFS
if [ -n "$FIND_BFS" ]; then
	got=$(bfs_ver "$FIND_BFS")
	if [ "$got" != "$want_bfs" ]; then
		echo "matrix-check: note — bfs $got != recorded $want_bfs, bfs column skipped"
		do_bfs=""
	fi
else
	echo "matrix-check: note — no bfs here, bfs column skipped"
fi

fails=0
while read -r t eF eG eB eX; do
	case "$t" in ''|'#'*) continue ;; esac
	gF=$(recog "$FER" 'unknown predicate' "$t")
	gG=$(recog "$GNU" 'unknown predicate' "$t")
	[ "$gF" = "$eF" ] || { echo "  MATRIX DRIFT $t: ferret $eF -> $gF"; fails=$((fails + 1)); }
	[ "$gG" = "$eG" ] || { echo "  MATRIX DRIFT $t: gnu $eG -> $gG"; fails=$((fails + 1)); }
	if [ -n "$do_bsd" ]; then
		gB=$(recog "$do_bsd" 'unknown primary or operator' "$t")
		[ "$gB" = "$eB" ] || { echo "  MATRIX DRIFT $t: bsd $eB -> $gB"; fails=$((fails + 1)); }
	fi
	if [ -n "$do_bfs" ]; then
		gX=$(recog "$do_bfs" 'Unknown argument' "$t")
		[ "$gX" = "$eX" ] || { echo "  MATRIX DRIFT $t: bfs $eX -> $gX"; fails=$((fails + 1)); }
	fi
done <"$tab"

if [ "$fails" -gt 0 ]; then
	echo "matrix-check: FAILED ($fails drifts vs matrix.tab — re-derive the classification)"
	exit 1
fi
echo "matrix-check: ok (ferret gnu${do_bsd:+ bsd}${do_bfs:+ bfs})"
exit 0
